demo_continuous(c(-1e6, 1e6), labels = label_number_de())
# scale_x_continuous(labels = label_number_de())
demo_continuous(c(-1e6, 1e6), labels = label_percent_de())
# scale_x_continuous(labels = label_percent_de())
#demo_continuous(c(-1e6, 1e6), labels = label_dollar_de())
# scale_x_continuous(labels = label_dollar_de())
