demo_number(c(-1e6, 1e6), scale_name = "number_de")
# scale_x_number_de()
demo_number(c(-1e6, 1e6), scale_name = "percent_de")
# scale_x_percent_de()
#demo_number(c(-1e6, 1e6), scale_name = "dollar_de")
# scale_x_dollar_de()
