demo_number(c(-1e6, 1e6), scale_name = "number_us")
# scale_x_number_us()
demo_number(c(-1, 1), scale_name = "percent_us")
# scale_x_percent_us()
demo_number(c(-1e4, 1e4), scale_name = "currency_us")
# scale_x_currency_us()
