demo_number(c(-1e6, 1e6), scale_name = "number_de")
# scale_x_number_de()
demo_number(c(-1, 1), scale_name = "percent_de")
# scale_x_percent_de()
demo_number(c(-1e4, 1e4), scale_name = "currency_de")
# scale_x_currency_de()
